import type { Metadata } from "next";
import { BotOrNotGame } from "../components/BotOrNotGame";
import { decodeProblem } from "../lib/shareProblem";

type PageProps = {
  searchParams?: Promise<Record<string, string | string[] | undefined>>;
};

export async function generateMetadata({
  searchParams,
}: PageProps): Promise<Metadata> {
  const params = await searchParams;
  const problemParam = firstParam(params?.problem);
  const sharedProblem = decodeProblem(problemParam);

  if (!problemParam || !sharedProblem) {
    return {
      title: "Bot or Not - Can You Spot the AI?",
      description: "Which row isn't truly random?",
    };
  }

  const image = `/api/og?problem=${encodeURIComponent(problemParam)}`;
  const pageTitle = "Bot or Not - Can You Spot the AI?";
  const socialTitle = "Which row isn't truly random?";
  const description = "One was generated by AI.";

  return {
    title: pageTitle,
    description,
    openGraph: {
      title: socialTitle,
      description,
      images: [
        {
          url: image,
          width: 1200,
          height: 630,
          alt: socialTitle,
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title: socialTitle,
      description,
      images: [image],
    },
  };
}

export default function Home() {
  return <BotOrNotGame />;
}

function firstParam(value: string | string[] | undefined) {
  return Array.isArray(value) ? value[0] : value;
}
