import { ImageResponse } from "next/og";
import {
  directionArrowPath,
  directionColor,
  directionRotation,
} from "../../../lib/directionVisuals";
import { decodeProblem, type SharedProblem } from "../../../lib/shareProblem";

export const runtime = "edge";

const labels = ["A", "B", "C", "D"];

export function GET(request: Request) {
  const url = new URL(request.url);
  const problem = decodeProblem(url.searchParams.get("problem"));

  return new ImageResponse(<OgCard problem={problem} />, {
    width: 1200,
    height: 630,
  });
}

function OgCard({ problem }: { problem: SharedProblem | null }) {
  return (
    <div
      style={{
        width: "100%",
        height: "100%",
        display: "flex",
        flexDirection: "column",
        padding: "54px 70px",
        color: "#151515",
        background: "#ffffff",
        fontFamily: "geist, Arial, sans-serif",
      }}
    >
      <div
        style={{
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
          marginBottom: 34,
        }}
      >
        <div
          style={{
            display: "flex",
            fontSize: 54,
            fontWeight: 800,
            lineHeight: 1,
          }}
        >
          Which row isn't truly random?
        </div>
        <div
          style={{
            display: "flex",
            marginTop: 14,
            color: "#666666",
            fontSize: 25,
            fontWeight: 600,
            lineHeight: 1,
          }}
        >
          One was generated by AI.
        </div>
      </div>

      <div
        style={{
          display: "flex",
          flexDirection: "column",
          gap: 16,
        }}
      >
        {problem ? (
          problem.o.map((sequence, index) => (
            <div
              key={`${labels[index]}-${sequence.join("-")}`}
              style={{
                height: 92,
                display: "flex",
                alignItems: "center",
                gap: 18,
                padding: "0 24px",
                border: "2px solid #e6e6e6",
                borderRadius: 16,
              }}
            >
              <div
                style={{
                  width: 38,
                  height: 38,
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  flexShrink: 0,
                  border: "2px solid #cfcfcf",
                  borderRadius: 999,
                  fontSize: 20,
                  fontWeight: 800,
                }}
              >
                {labels[index]}
              </div>
              {renderSequence(problem.c, sequence)}
            </div>
          ))
        ) : (
          <div
            style={{
              display: "flex",
              justifyContent: "center",
              color: "#777777",
              fontSize: 34,
              fontWeight: 700,
            }}
          >
            Open the link to play this Bot or Not challenge.
          </div>
        )}
      </div>
    </div>
  );
}

function renderSequence(categoryId: SharedProblem["c"], sequence: string[]) {
  switch (categoryId) {
    case "numbers":
      return (
        <div style={rowStyle(11)}>
          {sequence.map((token, index) => (
            <div key={`${token}-${index}`} style={numberStyle}>
              {token}
            </div>
          ))}
        </div>
      );
    case "digits":
      return (
        <div style={rowStyle(7)}>
          {sequence.map((token, index) => (
            <div key={`${token}-${index}`} style={digitStyle}>
              {token}
            </div>
          ))}
        </div>
      );
    case "colors":
      return (
        <div style={rowStyle(10)}>
          {sequence.map((token, index) => {
            const color = safeColor(token);

            return (
              <div
                key={`${token}-${index}`}
                style={{
                  ...colorStyle,
                  background: color,
                  color: colorText(color),
                }}
              >
                {token}
              </div>
            );
          })}
        </div>
      );
    case "coin_flips":
      return (
        <div style={rowStyle(8)}>
          {sequence.map((token, index) => (
            <div
              key={`${token}-${index}`}
              style={token === "H" ? coinHeadsStyle : coinTailsStyle}
            >
              {token}
            </div>
          ))}
        </div>
      );
    case "directions":
      return (
        <div style={rowStyle(18)}>
          {sequence.map((token, index) => (
            <div key={`${token}-${index}`} style={directionStyle}>
              <img
                alt=""
                src={directionSvgDataUrl(token)}
                style={directionIconStyle}
              />
            </div>
          ))}
        </div>
      );
    case "cards":
      return (
        <div style={rowStyle(12)}>
          {sequence.map((token, index) => {
            const card = parseCard(token);

            return (
              <div
                key={`${token}-${index}`}
                style={{
                  ...cardStyle,
                  color: card.red ? "#c7362f" : "#151515",
                }}
              >
                <div style={cardRankStyle}>{card.rank}</div>
                <div style={cardSuitStyle}>{card.suit}</div>
              </div>
            );
          })}
        </div>
      );
    case "dates":
      return (
        <div style={rowStyle(12)}>
          {sequence.map((token, index) => {
            const date = parseDateToken(token);

            return (
              <div key={`${token}-${index}`} style={dateStyle}>
                <div style={dateMonthStyle}>{date.month}</div>
                <div style={dateDayStyle}>{date.day}</div>
                <div style={dateYearStyle}>{date.year}</div>
              </div>
            );
          })}
        </div>
      );
  }
}

function rowStyle(gap: number) {
  return {
    display: "flex",
    flex: 1,
    gap,
    alignItems: "center",
    justifyContent: "space-between",
  };
}

const numberStyle = {
  width: 66,
  height: 66,
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  border: "2px solid #e6e6e6",
  borderRadius: 10,
  fontFamily: "Georgia, serif",
  fontSize: 34,
  fontWeight: 800,
};

const digitStyle = {
  width: 38,
  height: 42,
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  border: "2px solid #e6e6e6",
  borderRadius: 8,
  fontSize: 24,
  fontWeight: 800,
};

const colorStyle = {
  width: 98,
  height: 64,
  display: "flex",
  alignItems: "flex-end",
  justifyContent: "center",
  paddingBottom: 10,
  border: "2px solid rgba(21, 21, 21, 0.16)",
  borderRadius: 10,
  fontSize: 18,
  fontWeight: 900,
};

const coinBaseStyle = {
  width: 48,
  height: 48,
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  borderRadius: 999,
  fontSize: 22,
  fontWeight: 900,
};

const coinHeadsStyle = {
  ...coinBaseStyle,
  color: "#5f4514",
  background: "#d7aa3a",
  border: "2px solid #bc8e20",
};

const coinTailsStyle = {
  ...coinBaseStyle,
  color: "#4b4f57",
  background: "#c7ccd5",
  border: "2px solid #9aa1ad",
};

const directionStyle = {
  width: 50,
  height: 50,
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
};

const directionIconStyle = {
  width: 48,
  height: 48,
};

const cardStyle = {
  width: 86,
  height: 68,
  display: "flex",
  flexDirection: "column" as const,
  alignItems: "stretch",
  padding: "7px 8px",
  background: "#ffffff",
  border: "2px solid #d7d7d7",
  borderRadius: 10,
};

const cardRankStyle = {
  display: "flex",
  fontSize: 24,
  fontWeight: 800,
  lineHeight: 1,
};

const cardSuitStyle = {
  width: "100%",
  display: "flex",
  flex: 1,
  alignItems: "center",
  justifyContent: "center",
  fontSize: 31,
  lineHeight: 1,
};

const dateStyle = {
  width: 86,
  height: 68,
  display: "flex",
  flexDirection: "column" as const,
  alignItems: "center",
  justifyContent: "center",
  gap: 4,
  background: "#ffffff",
  border: "2px solid #e6e6e6",
  borderRadius: 10,
};

const dateMonthStyle = {
  color: "#777777",
  fontSize: 13,
  fontWeight: 900,
  textTransform: "uppercase" as const,
};

const dateDayStyle = {
  color: "#151515",
  fontSize: 28,
  fontWeight: 900,
  lineHeight: 0.9,
};

const dateYearStyle = {
  color: "#777777",
  fontSize: 13,
  fontWeight: 800,
};

function safeColor(value: string) {
  return /^#[0-9A-Fa-f]{6}$/.test(value) ? value : "#E5E7EB";
}

function colorText(value: string) {
  return hexLuminance(value) > 0.58 ? "#111111" : "#ffffff";
}

function hexLuminance(value: string) {
  const red = Number.parseInt(value.slice(1, 3), 16) / 255;
  const green = Number.parseInt(value.slice(3, 5), 16) / 255;
  const blue = Number.parseInt(value.slice(5, 7), 16) / 255;

  return 0.2126 * red + 0.7152 * green + 0.0722 * blue;
}

function directionSvgDataUrl(value: string) {
  const svg = [
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">',
    `<g transform="rotate(${directionRotation(value)} 32 32)">`,
    `<path d="${directionArrowPath}" fill="${directionColor(value)}"/>`,
    "</g>",
    "</svg>",
  ].join("");

  return `data:image/svg+xml;utf8,${encodeURIComponent(svg)}`;
}

function parseCard(token: string) {
  const suitCode = token.slice(-1);
  const rank = token.slice(0, -1);
  const suits: Record<string, string> = {
    C: "♣",
    D: "♦",
    H: "♥",
    S: "♠",
  };

  return {
    rank,
    suit: suits[suitCode] ?? suitCode,
    red: suitCode === "D" || suitCode === "H",
  };
}

function parseDateToken(token: string) {
  const [year = "", month = "", day = ""] = token.split("-");
  const monthNames = [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
  ];
  const monthIndex = Number(month) - 1;

  return {
    month: monthNames[monthIndex] ?? month,
    day: day.replace(/^0/, ""),
    year,
  };
}
